### ISSUE TITLE
Different versions in tags for the same commit

### ISSUE THREAD

**Issue by Trundle** [intel/intel-sgx-ssl#112]
I noticed that there are two different tags, [lin_2.16_1.1.1m](https://github.com/intel/intel-sgx-ssl/releases/tag/lin_2.16_1.1.1m) and  [win_2.15_1.1.1m](https://github.com/intel/intel-sgx-ssl/releases/tag/win_2.15_1.1.1m), both pointing to commit 6f36fd84b90ea06737398d8b9b3dd44abd50b7fe. Reading over the commits and given that there is no SGX release 2.16 yet, I assume that `lin_2.16_1.1.1m` was a typo and should be `lin_2.15_1.1.1m` instead.

**Comment by jinghe-INTC** [comment]
It was not a typo actually. The tags were the prereleases for SGX Linux 2.16 and Windows 2.15. SGX Linux 2.16 has just been released this week. Now you can use [SGXSSL lin_2.16_1.1.1m release version](https://github.com/intel/intel-sgx-ssl/releases/tag/lin_2.16_1.1.1m_update) with [SGX Linux 2.16](https://github.com/intel/linux-sgx/releases/tag/sgx_2.16).

The reason is that SGX has different version numbers for Linux and Windows, although released at the same time. For example the latest few releases:

- Apr 2022: SGX Linux 2.16 and SGX Windows 2.15
- Nov 2021: SGX Linux 2.15.1 and SGX Windows 2.14.1
- Sep 2021: SGX Linux 2.15 and SGX Windows 2.14
...
