### ISSUE TITLE
Migration doc for OpenSSL

### ISSUE THREAD

**Issue by 1178209138** [intel/intel-sgx-ssl#31]
Hi,
Is there any documentation or tips for migrating OpenSSL?Because I'm trying to migrate GmSSL(a branch of OpenSSL) to SGX,I think it would helps.

Thanks,
Yu

**Comment by akryeem-INTC** [comment]
You may take a look at SGXSSL design available in:[SGXSSL arch](https://github.com/intel/intel-sgx-ssl/blob/master/Intel(R)%20Software%20Guard%20Extensions%20SSL%20Library%20Architecture.pdf)
Basically, you need to bypass OS APIs and implement it using Intel SGX SDK APIs (since SGX Doesn't trust OS).
If you need further info/assist, let us know.

**Comment by 1178209138** [comment]
Thanks for your reply,it do helps : )
