### ISSUE TITLE
x509_verify_cert hanging on success

### ISSUE THREAD

**Issue by jbert145** [intel/intel-sgx-ssl#38]
Bit of a weird one here. I'm running Intel SGX (version 2.2) in simulation mode. Whenever I run x509_verify_cert, if it's verifying a certificate that should succeed, it hangs indefinitely. Failures work as expected.

The exact same code works correctly using standard OpenSSL, so I know that it's something to do with running it inside Intel SGX. I haven't noticed issues with any other functions.

I have a workaround for my project, so it's not in any way urgent, but it's probably worth looking into

Info:
SGX version 2.2
OpenSSL - 1.0.2g
SGX SSL - 1.1.1a
Ubuntu 16.04
Intel Core i5-3337U CPU @ 1.80GHz x 4

**Comment by akryeem-INTC** [comment]
Thanks for reporting this.
Is it possible to share a code snippet for this issue?

**Comment by Anthony-Mai** [comment]
I know no context of how this issue happens but wish to chip in to help. So whatever I expressed here is purely just my opinion. Parsing a certificate is a deterministic operation which should not hang for any reason, except for one. A certificate by itself cannot be fully authenticated, it needs to have the certificate signing body's certificate. A certificate signer's certificate itself also needs to be authenticated by yet another certificate. This is chain continues all the way to the root certificate which establish its trust by virtue of being stores in the system all the time and is trusted by default.

I think the problem is the codes look for but could not find the missing certificates, or could not get access, to have the full certificate chain for the authentication, and the code loops forever in hope of the root certificate becomes available at a later time.
